import type { Product } from "@/lib/types/product";

/** Set to false once real prices are confirmed */
export const USE_PLACEHOLDER_PRICES = true;

const PLACEHOLDER_BY_CATEGORY: Record<Product["category"], number> = {
  mens: 99,
  womens: 99,
  unisex: 49,
  gift: 149,
};

function withLaunchPricing(products: Product[]): Product[] {
  if (!USE_PLACEHOLDER_PRICES) return products;
  return products.map((p) => {
    const price = PLACEHOLDER_BY_CATEGORY[p.category] ?? 79;
    return { ...p, actual: price, original: price };
  });
}

const rawProducts: Product[] = [
  {
    id: "SA-001",
    name: "Zara Blue Temptation",
    actual: 350,
    original: 650,
    tag: "Men's Perfume",
    category: "mens",
    image: "/zara blue temptation.jpg",
    desc: "Clean, modern, and easygoing — a confident everyday scent for office, casual outings, and daily wear.",
    perfectOccasion: "Office, casual outings, everyday wear",
    pros: ["Clean modern profile", "Versatile day to evening", "Confident everyday scent", "Works in warm or mild weather"],
    cons: ["Best in mild climates", "Moderate projection"],
    whenToApply: [
      { icon: "Sun", label: "Daytime", detail: "Afternoon & early evening" },
      { icon: "Briefcase", label: "Office", detail: "Work & casual outings" },
      { icon: "Backpack", label: "Daily", detail: "Everyday wear" },
    ],
  },
  {
    id: "SA-002",
    name: "Azzaro Most Wanted EDT",
    actual: 1300,
    original: 1800,
    tag: "Men's Perfume",
    category: "mens",
    image: "/Azzaro most wanted EDT.jpg",
    desc: "Bold, attractive, and masculine — built for dates, parties, and special evening events.",
    perfectOccasion: "Dates, parties, special events",
    pros: ["Bold masculine appeal", "Strong evening presence", "Date-night favourite", "Confident projection"],
    cons: ["Best for cool evenings", "Not for hot daytime wear"],
    whenToApply: [
      { icon: "Moon", label: "Evening", detail: "Night events & parties" },
      { icon: "Heart", label: "Dates", detail: "Special occasions" },
      { icon: "PartyPopper", label: "Events", detail: "Parties & nights out" },
    ],
  },
  {
    id: "SA-003",
    name: "Givenchy Gentleman Society EDP",
    actual: 1200,
    original: 2000,
    tag: "Men's Perfume",
    category: "mens",
    image: "/Givenchy Gentleman Society EDP.jpg",
    desc: "Mature, refined, and classy — ideal for office, formal settings, and smart-casual wear.",
    perfectOccasion: "Office, formal settings, smart-casual",
    pros: ["Refined professional scent", "Mature and classy", "Day to evening versatility", "Strong office appeal"],
    cons: ["Premium price point", "Formal-leaning profile"],
    whenToApply: [
      { icon: "Briefcase", label: "Office", detail: "Professional settings" },
      { icon: "Landmark", label: "Formal", detail: "Smart-casual & formal" },
      { icon: "Sun", label: "Daytime", detail: "Mild to cool weather" },
    ],
  },
  {
    id: "SA-004",
    name: "Valentino Uomo Born in Roma Intense",
    actual: 1300,
    original: 2000,
    tag: "Men's Perfume",
    category: "mens",
    image: "/Valentino Uomo Born in Roma Intense.jpg",
    desc: "Stylish, expressive, and luxury-minded — made for dates, parties, and special occasions.",
    perfectOccasion: "Dates, parties, special occasions",
    pros: ["Luxury designer scent", "Bold evening character", "High compliment factor", "Expressive style"],
    cons: ["Premium investment", "Intense for casual daytime"],
    whenToApply: [
      { icon: "Moon", label: "Evening", detail: "Night occasions" },
      { icon: "Heart", label: "Dates", detail: "Romantic outings" },
      { icon: "PartyPopper", label: "Parties", detail: "Special events" },
    ],
  },
  {
    id: "SA-005",
    name: "JPG Le Male Le Parfum",
    actual: 650,
    original: 1200,
    tag: "Men's Perfume",
    category: "mens",
    image: "/JPG Le Male Le Parfum.jpg",
    desc: "Sexy, confident, playful, and charismatic — perfect for dates, clubs, and events.",
    perfectOccasion: "Dates, clubs, events",
    pros: ["Iconic masculine scent", "Playful and charismatic", "Strong night presence", "Great for social settings"],
    cons: ["Best in cool weather", "Bold signature"],
    whenToApply: [
      { icon: "Moon", label: "Night", detail: "Clubs & events" },
      { icon: "Heart", label: "Dates", detail: "Evening dates" },
      { icon: "PartyPopper", label: "Social", detail: "Nightlife & events" },
    ],
  },
  {
    id: "SA-006",
    name: "Boss The Scent Le Parfum",
    actual: 1100,
    original: 1800,
    tag: "Men's Perfume",
    category: "mens",
    image: "/Boss The Scent Le Parfum.jpg",
    desc: "Smooth, polished, neat, and masculine — suited for office, date night, and dinner.",
    perfectOccasion: "Office, date night, dinner",
    pros: ["Polished masculine blend", "Office to dinner versatility", "Smooth and neat", "Reliable longevity"],
    cons: ["Mild weather suits best", "Premium tier"],
    whenToApply: [
      { icon: "Briefcase", label: "Office", detail: "Professional wear" },
      { icon: "Heart", label: "Date Night", detail: "Dinners & evenings" },
      { icon: "Sun", label: "Daytime", detail: "Mild weather days" },
    ],
  },
  {
    id: "SA-007",
    name: "Spicebomb Extreme",
    actual: 600,
    original: 2000,
    tag: "Men's Perfume",
    category: "mens",
    image: "/Spicebomb Extreme.jpg",
    desc: "Strong, spicy, daring, and attention-grabbing — for dates, parties, and formal evening wear.",
    perfectOccasion: "Dates, parties, formal evening wear",
    pros: ["Powerful spicy profile", "Attention-grabbing sillage", "Bold evening statement", "Wide price range available"],
    cons: ["Very intense", "Not for office or heat"],
    whenToApply: [
      { icon: "Moon", label: "Night", detail: "Late evening wear" },
      { icon: "Heart", label: "Dates", detail: "Bold date nights" },
      { icon: "Landmark", label: "Formal", detail: "Formal evening events" },
    ],
  },
  {
    id: "SA-008",
    name: "Thameen Riviere",
    actual: 1500,
    original: 3000,
    tag: "Men's Perfume",
    category: "mens",
    image: "/Thameen Riviere.jpg",
    desc: "Elegant, niche, and sophisticated — crafted for luxury outings and special events.",
    perfectOccasion: "Luxury outings, special events",
    pros: ["Niche luxury quality", "Sophisticated elegance", "Special occasion worthy", "Distinctive character"],
    cons: ["Premium price", "Best for evening"],
    whenToApply: [
      { icon: "Moon", label: "Evening", detail: "Luxury outings" },
      { icon: "Landmark", label: "Special Events", detail: "Elevated occasions" },
      { icon: "Gift", label: "Gift Ready", detail: "Premium gifting" },
    ],
  },
  {
    id: "SA-009",
    name: "Bleu Talisman",
    actual: 1200,
    original: 2500,
    tag: "Men's Perfume",
    category: "mens",
    image: "/Bleu Talisman.jpg",
    desc: "Clean, modern, calm, and balanced — ideal for office and casual smart wear.",
    perfectOccasion: "Office, casual smart wear",
    pros: ["Clean balanced scent", "Modern office appeal", "Calm and refined", "Smart-casual friendly"],
    cons: ["Premium range", "Subtle projection"],
    whenToApply: [
      { icon: "Sun", label: "Daytime", detail: "Warm or mild days" },
      { icon: "Briefcase", label: "Office", detail: "Professional settings" },
      { icon: "ShoppingBag", label: "Smart Casual", detail: "Casual smart wear" },
    ],
  },
  {
    id: "SA-010",
    name: "Gucci Guilty Elixir Pour Homme",
    actual: 1440,
    original: 1800,
    tag: "Men's Perfume",
    category: "mens",
    image: "/Gucci Guilty Elixir Pour Homme.jpg",
    desc: "Bold, sensual, premium, and stylish — for dates, dinners, and luxury events.",
    perfectOccasion: "Dates, dinners, luxury events",
    pros: ["Premium designer elixir", "Sensual evening scent", "Stylish presence", "Luxury event ready"],
    cons: ["Evening-focused", "Premium price"],
    whenToApply: [
      { icon: "Moon", label: "Evening", detail: "Dinners & nights" },
      { icon: "Heart", label: "Dates", detail: "Romantic evenings" },
      { icon: "Landmark", label: "Luxury", detail: "High-end events" },
    ],
  },
  {
    id: "SA-011",
    name: "Liquid Brun",
    actual: 400,
    original: 900,
    tag: "Men's Perfume",
    category: "mens",
    image: "/Liquid Brun.jpg",
    desc: "Simple, smooth, and easygoing — great for casual wear, office, and relaxed outings.",
    perfectOccasion: "Casual, office, relaxed outings",
    pros: ["Affordable entry", "Smooth everyday scent", "Easy to wear", "Casual versatility"],
    cons: ["Light projection", "Simple profile"],
    whenToApply: [
      { icon: "Sun", label: "Daytime", detail: "Casual daily wear" },
      { icon: "Briefcase", label: "Office", detail: "Relaxed workdays" },
      { icon: "Backpack", label: "Casual", detail: "Easygoing outings" },
    ],
  },
  {
    id: "SA-012",
    name: "Khadlaj Island",
    actual: 350,
    original: 800,
    tag: "Unisex Body Spray",
    category: "unisex",
    image: "/Khadlaj Island.jpg",
    desc: "Fresh, relaxed, and approachable — perfect for casual outings and daily wear in warm weather.",
    perfectOccasion: "Casual outings, daily wear",
    pros: ["Fresh island vibe", "Warm weather friendly", "Approachable scent", "Great daily value"],
    cons: ["Casual wear only", "Moderate longevity"],
    whenToApply: [
      { icon: "Sun", label: "Daytime", detail: "Warm weather days" },
      { icon: "ShoppingBag", label: "Casual", detail: "Outings & errands" },
      { icon: "Backpack", label: "Daily", detail: "Everyday spray" },
    ],
  },
  {
    id: "SA-013",
    name: "Fashionably London Elixir",
    actual: 350,
    original: 900,
    tag: "Men's Perfume",
    category: "mens",
    image: "/Fashionably London Elixir.jpg",
    desc: "Trendy, stylish, and youthful — made for dates and social outings in mild to cool weather.",
    perfectOccasion: "Dates, social outings",
    pros: ["Trendy youthful scent", "Social outing ready", "Affordable elixir", "Stylish appeal"],
    cons: ["Evening-leaning", "Youthful profile"],
    whenToApply: [
      { icon: "Moon", label: "Evening", detail: "Social outings" },
      { icon: "Heart", label: "Dates", detail: "Night dates" },
      { icon: "PartyPopper", label: "Social", detail: "Hangouts & events" },
    ],
  },
  {
    id: "SA-014",
    name: "9PM Rebel",
    actual: 300,
    original: 700,
    tag: "Unisex Body Spray",
    category: "unisex",
    image: "/9PM Rebel.jpg",
    desc: "Fun, loud, youthful, and bold — built for parties, clubbing, and late-night hangouts.",
    perfectOccasion: "Parties, clubbing, hangouts",
    pros: ["Bold party scent", "Youthful energy", "Budget-friendly", "Nightlife ready"],
    cons: ["Night use only", "Not for formal settings"],
    whenToApply: [
      { icon: "Moon", label: "Night", detail: "Clubbing & parties" },
      { icon: "PartyPopper", label: "Parties", detail: "Late-night hangouts" },
      { icon: "Heart", label: "Social", detail: "Bold nights out" },
    ],
  },
  {
    id: "SA-015",
    name: "Davidoff Cool Water",
    actual: 250,
    original: 600,
    tag: "Men's Perfume",
    category: "mens",
    image: "/Davidoff Cool Water.jpg",
    desc: "Fresh, clean, and simple — a classic for casual wear, office, and daily use in hot weather.",
    perfectOccasion: "Casual, office, daily use",
    pros: ["Iconic fresh scent", "Hot weather friendly", "Clean and simple", "Great starter fragrance"],
    cons: ["Common profile", "Moderate longevity"],
    whenToApply: [
      { icon: "Sunrise", label: "Morning", detail: "Fresh daily start" },
      { icon: "Sun", label: "Daytime", detail: "Hot weather wear" },
      { icon: "Briefcase", label: "Office", detail: "Casual office days" },
    ],
  },
  {
    id: "SA-016",
    name: "Blue de Beautiful Girl",
    actual: 150,
    original: 400,
    tag: "Women's Perfume",
    category: "womens",
    image: "/perfume.jpg",
    desc: "Soft, youthful, and feminine — ideal for casual outings, school, and everyday errands.",
    perfectOccasion: "Casual outings, school, errands",
    pros: ["Most affordable feminine option", "Soft youthful scent", "Everyday friendly", "Light and approachable"],
    cons: ["Light longevity", "Casual profile only"],
    whenToApply: [
      { icon: "Sun", label: "Daytime", detail: "Warm weather days" },
      { icon: "GraduationCap", label: "School", detail: "Campus & errands" },
      { icon: "ShoppingBag", label: "Casual", detail: "Everyday outings" },
    ],
  },
  {
    id: "SA-017",
    name: "Eclive",
    actual: 200,
    original: 500,
    tag: "Unisex Body Spray",
    category: "unisex",
    image: "/perfume.jpg",
    desc: "Simple, balanced, and easygoing — suited for casual wear, office, and everyday use.",
    perfectOccasion: "Casual, office, everyday use",
    pros: ["Balanced everyday scent", "Office appropriate", "Affordable spray", "Easygoing character"],
    cons: ["Subtle projection", "Basic profile"],
    whenToApply: [
      { icon: "Sun", label: "Daytime", detail: "Warm or mild days" },
      { icon: "Briefcase", label: "Office", detail: "Everyday work" },
      { icon: "Backpack", label: "Daily", detail: "Casual daily use" },
    ],
  },
  {
    id: "SA-018",
    name: "9PM Elixir",
    actual: 350,
    original: 800,
    tag: "Unisex Body Spray",
    category: "unisex",
    image: "/9PM Elixir.jpg",
    desc: "Sweet, bold, youthful, and attractive — for parties, dates, and evening events.",
    perfectOccasion: "Parties, dates, evening events",
    pros: ["Sweet evening appeal", "Youthful and bold", "Date-night friendly", "Good value elixir"],
    cons: ["Evening-focused", "Sweet profile"],
    whenToApply: [
      { icon: "Moon", label: "Night", detail: "Evening events" },
      { icon: "Heart", label: "Dates", detail: "Attractive nights out" },
      { icon: "PartyPopper", label: "Parties", detail: "Social evenings" },
    ],
  },
  {
    id: "SA-019",
    name: "Matelot",
    actual: 200,
    original: 500,
    tag: "Men's Perfume",
    category: "mens",
    image: "/Matelot.jpg",
    desc: "Fresh, simple, and masculine — an easy choice for casual daily wear in warm weather.",
    perfectOccasion: "Casual daily wear",
    pros: ["Fresh masculine scent", "Affordable daily option", "Simple and clean", "Warm weather suited"],
    cons: ["Casual only", "Moderate wear time"],
    whenToApply: [
      { icon: "Sun", label: "Daytime", detail: "Warm weather days" },
      { icon: "Backpack", label: "Daily", detail: "Casual daily wear" },
      { icon: "ShoppingBag", label: "Casual", detail: "Relaxed outings" },
    ],
  },
  {
    id: "SA-020",
    name: "Dark Brown Orchid",
    actual: 250,
    original: 700,
    tag: "Women's Perfume",
    category: "womens",
    image: "/Dark Brown Orchid.jpg",
    desc: "Rich, deep, sexy, and classy — perfect for dates, formal outings, and luxury events.",
    perfectOccasion: "Dates, formal outings, luxury events",
    pros: ["Rich deep florals", "Classy evening scent", "Date-night appeal", "Luxury event ready"],
    cons: ["Evening-focused", "Bold profile"],
    whenToApply: [
      { icon: "Moon", label: "Evening", detail: "Night occasions" },
      { icon: "Heart", label: "Dates", detail: "Formal date nights" },
      { icon: "Landmark", label: "Luxury", detail: "Upscale events" },
    ],
  },
  {
    id: "SA-021",
    name: "Marshmallow Blush",
    actual: 250,
    original: 700,
    tag: "Women's Perfume",
    category: "womens",
    image: "/Marshmallow Blush.jpg",
    desc: "Sweet, playful, soft, and romantic — lovely for casual wear, day dates, and feminine outings.",
    perfectOccasion: "Casual, day dates, feminine outings",
    pros: ["Sweet romantic scent", "Playful and soft", "Day-date friendly", "Feminine charm"],
    cons: ["Sweet in hot weather", "Casual to soft evening only"],
    whenToApply: [
      { icon: "Sun", label: "Daytime", detail: "Soft daytime wear" },
      { icon: "Heart", label: "Day Dates", detail: "Romantic outings" },
      { icon: "ShoppingBag", label: "Casual", detail: "Feminine everyday wear" },
    ],
  },
];

export const allProducts = withLaunchPricing(rawProducts);
