import type { Product } from "@/lib/types/product";

/** Set to false once real prices are confirmed */
export const USE_PLACEHOLDER_PRICES = false;

const PLACEHOLDER_BY_CATEGORY: Record<Product["category"], number> = {
  mens: 99,
  womens: 99,
  unisex: 49,
  gift: 149,
};

function withLaunchPricing(products: Product[]): Product[] {
  if (!USE_PLACEHOLDER_PRICES) return products;
  return products.map((p) => {
    const price = PLACEHOLDER_BY_CATEGORY[p.category] ?? 79;
    return { ...p, actual: price, original: price };
  });
}

const rawProducts: Product[] = [
  {
    id: "SA-001",
    name: "Zara Blue Temptation",
    actual: 180,
    original: 300,
    tag: "Men's Perfume",
    category: "mens",
    image: "/zara blue temptation.jpg",
    desc: "Clean, modern, and easygoing — a confident everyday scent for office, casual outings, and daily wear in Ghana.",
    perfectOccasion: "Office, casual outings, everyday wear",
    pros: ["Clean modern profile", "Versatile day to evening", "Confident everyday scent", "Works in warm Ghanaian weather"],
    cons: ["Best in mild climates", "Moderate projection"],
    whenToApply: [
      { icon: "Sun", label: "Daytime", detail: "Afternoon & early evening" },
      { icon: "Briefcase", label: "Office", detail: "Work & casual outings" },
      { icon: "Backpack", label: "Daily", detail: "Everyday wear" },
    ],
  },
  {
    id: "SA-002",
    name: "Azzaro The Most Wanted",
    actual: 380,
    original: 640,
    tag: "Men's Perfume",
    category: "mens",
    image: "/Azzaro most wanted EDT.jpg",
    desc: "Bold, sweet, spicy, and seductive — built for night events, parties, and date nights in Accra.",
    perfectOccasion: "Dates, parties, special events",
    pros: ["Bold masculine appeal", "Strong evening presence", "Date-night favourite", "Confident projection"],
    cons: ["Best for cool evenings", "Not for hot daytime wear"],
    whenToApply: [
      { icon: "Moon", label: "Evening", detail: "Night events & parties" },
      { icon: "Heart", label: "Dates", detail: "Special occasions" },
      { icon: "PartyPopper", label: "Events", detail: "Parties & nights out" },
    ],
  },
  {
    id: "SA-003",
    name: "Givenchy Gentleman Society EDP",
    actual: 390,
    original: 650,
    tag: "Men's Perfume",
    category: "mens",
    image: "/Givenchy Gentleman Society EDP.jpg",
    desc: "Mature, refined, and classy — ideal for executive office meetings, formal events, and smart occasions.",
    perfectOccasion: "Office, formal settings, smart-casual",
    pros: ["Refined professional scent", "Mature and classy", "Day to evening versatility", "Strong office appeal"],
    cons: ["Premium price point", "Formal-leaning profile"],
    whenToApply: [
      { icon: "Briefcase", label: "Office", detail: "Professional settings" },
      { icon: "Landmark", label: "Formal", detail: "Smart-casual & formal" },
      { icon: "Sun", label: "Daytime", detail: "Mild to cool weather" },
    ],
  },
  {
    id: "SA-004",
    name: "Valentino Born In Roma Intense",
    actual: 390,
    original: 650,
    tag: "Men's Perfume",
    category: "mens",
    image: "/Valentino Uomo Born in Roma Intense.jpg",
    desc: "Stylish, expressive, and luxury-minded — vanilla, vetiver, and lavender made for dates and luxury outings.",
    perfectOccasion: "Dates, parties, special occasions",
    pros: ["Luxury designer scent", "Bold evening character", "High compliment factor", "Expressive style"],
    cons: ["Premium investment", "Intense for casual daytime"],
    whenToApply: [
      { icon: "Moon", label: "Evening", detail: "Night occasions" },
      { icon: "Heart", label: "Dates", detail: "Romantic outings" },
      { icon: "PartyPopper", label: "Parties", detail: "Special events" },
    ],
  },
  {
    id: "SA-005",
    name: "Jean Paul Gaultier Le Male Le Parfum",
    actual: 330,
    original: 550,
    tag: "Men's Perfume",
    category: "mens",
    image: "/JPG Le Male Le Parfum.jpg",
    desc: "Cardamom, lavender, iris, and vanilla — iconic, sensual, and charismatic date night favorite.",
    perfectOccasion: "Dates, clubs, evening events",
    pros: ["Iconic masculine scent", "Playful and charismatic", "Strong night presence", "Huge crowd puller"],
    cons: ["Best in cool evenings", "Bold signature"],
    whenToApply: [
      { icon: "Moon", label: "Night", detail: "Clubs & events" },
      { icon: "Heart", label: "Dates", detail: "Evening dates" },
      { icon: "PartyPopper", label: "Social", detail: "Nightlife & events" },
    ],
  },
  {
    id: "SA-006",
    name: "Hugo Boss The Scent Le Parfum",
    actual: 340,
    original: 570,
    tag: "Men's Perfume",
    category: "mens",
    image: "/Boss The Scent Le Parfum.jpg",
    desc: "Smooth Maninka fruit, leather, and iris — polished, neat, and masculine for work and dinner.",
    perfectOccasion: "Office, date night, dinner",
    pros: ["Polished masculine blend", "Office to dinner versatility", "Smooth and neat", "Reliable longevity"],
    cons: ["Mild weather suits best", "Premium tier"],
    whenToApply: [
      { icon: "Briefcase", label: "Office", detail: "Professional wear" },
      { icon: "Heart", label: "Date Night", detail: "Dinners & evenings" },
      { icon: "Sun", label: "Daytime", detail: "Mild weather days" },
    ],
  },
  {
    id: "SA-007",
    name: "Viktor & Rolf Spicebomb Extreme",
    actual: 360,
    original: 600,
    tag: "Men's Perfume",
    category: "mens",
    image: "/Spicebomb Extreme.jpg",
    desc: "Black pepper, cinnamon, tobacco, and bourbon vanilla — explosive, spicy, daring, and long-lasting.",
    perfectOccasion: "Dates, parties, formal evening wear",
    pros: ["Powerful spicy profile", "Attention-grabbing sillage", "Bold evening statement", "Unbeatable winter/night performance"],
    cons: ["Very intense", "Not for hot sunny afternoons"],
    whenToApply: [
      { icon: "Moon", label: "Night", detail: "Late evening wear" },
      { icon: "Heart", label: "Dates", detail: "Bold date nights" },
      { icon: "Landmark", label: "Formal", detail: "Formal evening events" },
    ],
  },
  {
    id: "SA-008",
    name: "Thameen Riviere",
    actual: 420,
    original: 700,
    tag: "Men's Perfume",
    category: "mens",
    image: "/Thameen Riviere.jpg",
    desc: "Black pepper, saffron, sage, and Turkish rose — elegant British niche luxury for high-end celebrations.",
    perfectOccasion: "Luxury outings, special events, weddings",
    pros: ["Niche luxury quality", "Sophisticated elegance", "Special occasion worthy", "Distinctive character"],
    cons: ["Premium price", "Best for evening"],
    whenToApply: [
      { icon: "Moon", label: "Evening", detail: "Luxury outings" },
      { icon: "Landmark", label: "Special Events", detail: "Elevated occasions" },
      { icon: "Gift", label: "Gift Ready", detail: "Premium gifting" },
    ],
  },
  {
    id: "SA-009",
    name: "Bleu Talisman (Ex Nihilo)",
    actual: 320,
    original: 540,
    tag: "Men's Perfume",
    category: "mens",
    image: "/Bleu Talisman.jpg",
    desc: "Bergamot, ginger, cedarwood, and Akigalawood — clean, ultra-modern, crisp, and high compliments.",
    perfectOccasion: "Office, casual smart wear, church & day outings",
    pros: ["Clean balanced scent", "Modern office appeal", "Calm and refined", "Smart-casual friendly"],
    cons: ["Premium range", "Subtle projection"],
    whenToApply: [
      { icon: "Sun", label: "Daytime", detail: "Warm or mild days" },
      { icon: "Briefcase", label: "Office", detail: "Professional settings" },
      { icon: "ShoppingBag", label: "Smart Casual", detail: "Casual smart wear" },
    ],
  },
  {
    id: "SA-010",
    name: "Gucci Guilty Elixir Pour Homme",
    actual: 420,
    original: 700,
    tag: "Men's Perfume",
    category: "mens",
    image: "/Gucci Guilty Elixir Pour Homme.jpg",
    desc: "Orange blossom, nutmeg, pimento, and rich vanillin — opulent, intoxicating, and stylish designer elixir.",
    perfectOccasion: "Dates, dinners, luxury events",
    pros: ["Premium designer elixir", "Sensual evening scent", "Stylish presence", "Luxury event ready"],
    cons: ["Evening-focused", "Premium price"],
    whenToApply: [
      { icon: "Moon", label: "Evening", detail: "Dinners & nights" },
      { icon: "Heart", label: "Dates", detail: "Romantic evenings" },
      { icon: "Landmark", label: "Luxury", detail: "High-end events" },
    ],
  },
  {
    id: "SA-011",
    name: "French Avenue Liquid Brun",
    actual: 220,
    original: 370,
    tag: "Men's Perfume",
    category: "mens",
    image: "/Liquid Brun.jpg",
    desc: "Cinnamon, cardamom, orange blossom, and bourbon vanilla — famous viral clone of Althair.",
    perfectOccasion: "Casual, office, relaxed outings, dates",
    pros: ["Smooth vanilla spice", "Huge viral favorite", "Easy to wear", "High compliment rate"],
    cons: ["Sweet profile", "Best in cool environment"],
    whenToApply: [
      { icon: "Sun", label: "Daytime", detail: "Casual daily wear" },
      { icon: "Briefcase", label: "Office", detail: "Relaxed workdays" },
      { icon: "Backpack", label: "Casual", detail: "Easygoing outings" },
    ],
  },
  {
    id: "SA-012",
    name: "Khadlaj Island Body Mist",
    actual: 160,
    original: 270,
    tag: "Unisex Body Spray",
    category: "unisex",
    image: "/Khadlaj Island.jpg",
    desc: "Tropical coconut, sea breeze, and sunny musk — fresh, relaxed, and approachable for sunny Ghana days.",
    perfectOccasion: "Casual outings, beach days, daily wear",
    pros: ["Fresh island vibe", "Warm weather friendly", "Approachable scent", "Great daily value"],
    cons: ["Casual wear only", "Moderate longevity"],
    whenToApply: [
      { icon: "Sun", label: "Daytime", detail: "Warm weather days" },
      { icon: "ShoppingBag", label: "Casual", detail: "Outings & errands" },
      { icon: "Backpack", label: "Daily", detail: "Everyday spray" },
    ],
  },
  {
    id: "SA-013",
    name: "Zara Fashionably London",
    actual: 210,
    original: 350,
    tag: "Men's Perfume",
    category: "mens",
    image: "/Fashionably London Elixir.jpg",
    desc: "Bergamot, rose, and musk by Jo Malone for Zara — stylish, crisp, modern, and energetic.",
    perfectOccasion: "Dates, social outings, church, brunch",
    pros: ["Trendy youthful scent", "Social outing ready", "Affordable luxury", "Stylish appeal"],
    cons: ["Evening-leaning", "Moderate longevity"],
    whenToApply: [
      { icon: "Moon", label: "Evening", detail: "Social outings" },
      { icon: "Heart", label: "Dates", detail: "Night dates" },
      { icon: "PartyPopper", label: "Social", detail: "Hangouts & events" },
    ],
  },
  {
    id: "SA-014",
    name: "Afnan 9PM Rebel",
    actual: 150,
    original: 250,
    tag: "Unisex Body Spray",
    category: "unisex",
    image: "/9PM Rebel.jpg",
    desc: "Pineapple, granny smith apple, and caramel woods — vibrant, bold, and energetic party mist.",
    perfectOccasion: "Parties, clubbing, hangout sessions",
    pros: ["Bold party scent", "Youthful energy", "Budget-friendly", "Nightlife ready"],
    cons: ["Night use only", "Not for formal settings"],
    whenToApply: [
      { icon: "Moon", label: "Night", detail: "Clubbing & parties" },
      { icon: "PartyPopper", label: "Parties", detail: "Late-night hangouts" },
      { icon: "Heart", label: "Social", detail: "Bold nights out" },
    ],
  },
  {
    id: "SA-015",
    name: "Davidoff Cool Water Man",
    actual: 180,
    original: 300,
    tag: "Men's Perfume",
    category: "mens",
    image: "/Davidoff Cool Water.jpg",
    desc: "Peppermint, lavender, seawater, and cedarwood — the timeless aquatic classic for Ghana's weather.",
    perfectOccasion: "Casual, office, gym, daily use",
    pros: ["Iconic fresh scent", "Hot weather friendly", "Clean and simple", "Universal everyday wear"],
    cons: ["Classic scent profile", "Moderate longevity"],
    whenToApply: [
      { icon: "Sunrise", label: "Morning", detail: "Fresh daily start" },
      { icon: "Sun", label: "Daytime", detail: "Hot weather wear" },
      { icon: "Briefcase", label: "Office", detail: "Casual office days" },
    ],
  },
  {
    id: "SA-016",
    name: "Blue de Beautiful Girl EDP",
    actual: 120,
    original: 200,
    tag: "Women's Perfume",
    category: "womens",
    image: "/perfume.jpg",
    desc: "Soft floral nectar, clean musk, and sweet vanilla — lovely budget everyday fragrance for ladies.",
    perfectOccasion: "Casual outings, campus, daily errands",
    pros: ["Most affordable feminine option", "Soft youthful scent", "Everyday friendly", "Light and approachable"],
    cons: ["Light longevity", "Casual profile only"],
    whenToApply: [
      { icon: "Sun", label: "Daytime", detail: "Warm weather days" },
      { icon: "GraduationCap", label: "School", detail: "Campus & errands" },
      { icon: "ShoppingBag", label: "Casual", detail: "Everyday outings" },
    ],
  },
  {
    id: "SA-017",
    name: "Eclive De Paris Spray",
    actual: 120,
    original: 200,
    tag: "Unisex Body Spray",
    category: "unisex",
    image: "/perfume.jpg",
    desc: "Fresh citrus and amber musk — clean and energizing everyday body spray for daily freshening.",
    perfectOccasion: "Casual, office, daily freshening",
    pros: ["Balanced everyday scent", "Office appropriate", "Affordable spray", "Easygoing character"],
    cons: ["Subtle projection", "Basic profile"],
    whenToApply: [
      { icon: "Sun", label: "Daytime", detail: "Warm or mild days" },
      { icon: "Briefcase", label: "Office", detail: "Everyday work" },
      { icon: "Backpack", label: "Daily", detail: "Casual daily use" },
    ],
  },
  {
    id: "SA-018",
    name: "Afnan 9PM Elixir",
    actual: 180,
    original: 300,
    tag: "Unisex Body Spray",
    category: "unisex",
    image: "/9PM Elixir.jpg",
    desc: "Wild lavender, apple, cinnamon, and warm amber — super viral sweet evening clubbing DNA in a spray.",
    perfectOccasion: "Parties, dates, evening events",
    pros: ["Sweet evening appeal", "Youthful and bold", "Date-night friendly", "Viral 9PM scent DNA"],
    cons: ["Evening-focused", "Sweet profile"],
    whenToApply: [
      { icon: "Moon", label: "Night", detail: "Evening events" },
      { icon: "Heart", label: "Dates", detail: "Attractive nights out" },
      { icon: "PartyPopper", label: "Parties", detail: "Social evenings" },
    ],
  },
  {
    id: "SA-019",
    name: "Matelot Pour Homme",
    actual: 150,
    original: 250,
    tag: "Men's Perfume",
    category: "mens",
    image: "/Matelot.jpg",
    desc: "Oceanic fresh citrus and woody notes — straightforward, clean, and reliable for Ghanaian daytime heat.",
    perfectOccasion: "Casual daily wear, work, sports",
    pros: ["Fresh masculine scent", "Affordable daily option", "Simple and clean", "Warm weather suited"],
    cons: ["Casual only", "Moderate wear time"],
    whenToApply: [
      { icon: "Sun", label: "Daytime", detail: "Warm weather days" },
      { icon: "Backpack", label: "Daily", detail: "Casual daily wear" },
      { icon: "ShoppingBag", label: "Casual", detail: "Relaxed outings" },
    ],
  },
  {
    id: "SA-020",
    name: "Dark Brown Orchid (Fragrance World)",
    actual: 190,
    original: 320,
    tag: "Women's Perfume",
    category: "womens",
    image: "/Dark Brown Orchid.jpg",
    desc: "Black truffle, ylang-ylang, dark chocolate, and patchouli — rich, mysterious, and seductive.",
    perfectOccasion: "Dates, church, formal outings, weddings",
    pros: ["Tom Ford Black Orchid vibe", "Rich deep florals", "Classy evening scent", "Long lasting on clothes"],
    cons: ["Evening-focused", "Deep and bold profile"],
    whenToApply: [
      { icon: "Moon", label: "Evening", detail: "Night occasions" },
      { icon: "Heart", label: "Dates", detail: "Formal date nights" },
      { icon: "Landmark", label: "Luxury", detail: "Upscale events" },
    ],
  },
  {
    id: "SA-021",
    name: "Marshmallow Blush (Fragrance World)",
    actual: 180,
    original: 300,
    tag: "Women's Perfume",
    category: "womens",
    image: "/Marshmallow Blush.jpg",
    desc: "Marshmallows, strawberries, whipped vanilla cream, and soft musk — ultra-sweet and delicious.",
    perfectOccasion: "Casual, day dates, brunch, shopping",
    pros: ["Sweet gourmand strawberry vibe", "Playful and soft", "Day-date friendly", "Feminine crowd favorite"],
    cons: ["Sweet in hot afternoons", "Youthful gourmand profile"],
    whenToApply: [
      { icon: "Sun", label: "Daytime", detail: "Soft daytime wear" },
      { icon: "Heart", label: "Day Dates", detail: "Romantic outings" },
      { icon: "ShoppingBag", label: "Casual", detail: "Feminine everyday wear" },
    ],
  },
  {
    id: "SA-022",
    name: "Lattafa Khamrah Eau De Parfum",
    actual: 280,
    original: 470,
    tag: "Unisex Perfume",
    category: "unisex",
    image: "/perfume1.jpg",
    desc: "Cinnamon, nutmeg, dates, praline, and vanilla — the viral #1 best-selling Arabian gourmand perfume in Ghana.",
    perfectOccasion: "Evening dinners, church, cold weather, luxury events",
    pros: ["Massive 12+ hours longevity", "Rich dates and praline notes", "Huge compliment getter", "Stunning crystal bottle"],
    cons: ["Very sweet profile", "Best for air-conditioned & evening settings"],
    whenToApply: [
      { icon: "Moon", label: "Evening", detail: "Date nights & dinners" },
      { icon: "Heart", label: "Romantic", detail: "Sensual statement" },
      { icon: "Landmark", label: "Occasions", detail: "Celebrations & events" },
    ],
  },
  {
    id: "SA-023",
    name: "Baccarat Rouge 540 Extrait",
    actual: 280,
    original: 470,
    tag: "Women's Perfume",
    category: "womens",
    image: "/perfume2.jpg",
    desc: "Bitter almond, grandiflorum jasmine, saffron, and ambergris — the ultimate viral luxury status symbol fragrance.",
    perfectOccasion: "Red carpet, weddings, VIP dinners, luxury dates",
    pros: ["Legendary sillage & projection", "Saffron and ambergris aura", "Radiates pure wealth", "Lasts for days on fabric"],
    cons: ["Intense projection", "Signature luxury scent"],
    whenToApply: [
      { icon: "Moon", label: "Night", detail: "Luxury evening events" },
      { icon: "Heart", label: "Dates", detail: "Special dates" },
      { icon: "PartyPopper", label: "Parties", detail: "Nightlife" },
    ],
  },
  {
    id: "SA-024",
    name: "Armaf Club de Nuit Intense Man",
    actual: 270,
    original: 450,
    tag: "Men's Perfume",
    category: "mens",
    image: "/perfume3.jpg",
    desc: "Lemon, blackcurrant, birch, and musk — the undisputed #1 men's compliment beast in Ghana.",
    perfectOccasion: "Office, church, weddings, dates, everyday boss scent",
    pros: ["Unstoppable compliment getter", "Beast-mode 10+ hours projection", "Smoky fruity profile", "Dominates any room"],
    cons: ["Strong opening 10 mins", "Potent projection"],
    whenToApply: [
      { icon: "Briefcase", label: "Office", detail: "Executive presence" },
      { icon: "Sun", label: "Daytime", detail: "All-day signature" },
      { icon: "Moon", label: "Evening", detail: "Night gatherings" },
    ],
  },
  {
    id: "SA-025",
    name: "Lattafa Yara Pink Eau De Parfum",
    actual: 210,
    original: 350,
    tag: "Women's Perfume",
    category: "womens",
    image: "/perfum4.jpg",
    desc: "Heliotrope, orchid, tropical fruits, and vanilla cream — Ghana's most viral TikTok women's perfume.",
    perfectOccasion: "Brunch, shopping, everyday feminine charm, work",
    pros: ["Soft strawberry milkshake sweetness", "Pleasant everyday scent", "High crowd appeal", "Gentle projection"],
    cons: ["Moderate longevity", "Sweet gourmand lovers"],
    whenToApply: [
      { icon: "Sun", label: "Daytime", detail: "Day outings & shopping" },
      { icon: "ShoppingBag", label: "Casual", detail: "Brunch & lunch dates" },
      { icon: "Heart", label: "Dates", detail: "Romantic daytime vibes" },
    ],
  },
  {
    id: "SA-026",
    name: "Tom Ford Lost Cherry",
    actual: 250,
    original: 420,
    tag: "Women's Perfume",
    category: "womens",
    image: "/perfume5.jpg",
    desc: "Black cherry liqueur, bitter almond, Turkish rose, and roasted tonka — dark, playful, and deeply seductive.",
    perfectOccasion: "Date nights, cocktail lounges, glamorous evenings",
    pros: ["Intoxicating dark cherry aroma", "Unique seductive character", "Warm spicy base", "Compliment magnet"],
    cons: ["Best in evening", "Rich and decadent"],
    whenToApply: [
      { icon: "Moon", label: "Evening", detail: "Cocktail nights & lounges" },
      { icon: "Heart", label: "Romantic", detail: "Intimate dates" },
      { icon: "PartyPopper", label: "Events", detail: "Special celebrations" },
    ],
  },
  {
    id: "SA-027",
    name: "MFK Gentle Fluidity Gold",
    actual: 260,
    original: 440,
    tag: "Unisex Perfume",
    category: "unisex",
    image: "/perfume6.jpg",
    desc: "Juniper berries, nutmeg, coriander, musk, and amber vanilla — effortless golden luxury that leaves an angelic trail.",
    perfectOccasion: "Executive meetings, upscale dinners, Sunday best",
    pros: ["Velvety smooth vanilla & amber", "Subtle yet persistent", "Quiet luxury aesthetic", "Genderless appeal"],
    cons: ["Intimate sillage", "Understated elegance"],
    whenToApply: [
      { icon: "Sun", label: "Daytime", detail: "Quiet luxury presence" },
      { icon: "Briefcase", label: "Office", detail: "Corporate & client meetings" },
      { icon: "Moon", label: "Evening", detail: "Dinner dates" },
    ],
  },
  {
    id: "SA-028",
    name: "Lattafa Asad Eau De Parfum",
    actual: 240,
    original: 400,
    tag: "Men's Perfume",
    category: "mens",
    image: "/perfume7.jpg",
    desc: "Black pepper, pineapple, tobacco, coffee, and amberwood — the famous dark spicy Sauvage Elixir alternative.",
    perfectOccasion: "Evening hangouts, church, dates, formal events",
    pros: ["Spicy dark coffee and tobacco accord", "Excellent longevity", "Deep masculine vibe", "Unbeatable value"],
    cons: ["Not for hot afternoons", "Strong spices"],
    whenToApply: [
      { icon: "Moon", label: "Night", detail: "Club & evening parties" },
      { icon: "Landmark", label: "Formal", detail: "Banquets & dinners" },
      { icon: "Heart", label: "Dates", detail: "Bold date nights" },
    ],
  },
  {
    id: "SA-029",
    name: "Parfums de Marly Delina Exclusif",
    actual: 280,
    original: 470,
    tag: "Women's Perfume",
    category: "womens",
    image: "/perfume8.jpg",
    desc: "Lychee, pear, Turkish rose, incense, and amber vanilla — regal, ultra-feminine, and pure luxury.",
    perfectOccasion: "Weddings, anniversary dinners, luxury celebrations",
    pros: ["Fresh tart lychee & royal rose", "Beast-mode longevity for florals", "Luxurious compliment trail", "Regal feel"],
    cons: ["Strong initial floral burst", "Special occasion leaning"],
    whenToApply: [
      { icon: "Sun", label: "Daytime", detail: "Garden parties & weddings" },
      { icon: "Heart", label: "Romantic", detail: "Anniversaries" },
      { icon: "Landmark", label: "Formal", detail: "Upscale functions" },
    ],
  },
  {
    id: "SA-030",
    name: "Armani Stronger With You Intensely",
    actual: 290,
    original: 490,
    tag: "Men's Perfume",
    category: "mens",
    image: "/perfume9.jpg",
    desc: "Pink pepper, toffee, cinnamon, and lavender — viral cozy date night favorite that women find irresistible.",
    perfectOccasion: "Dates, cinema, cozy evenings, dinner",
    pros: ["Addictive toffee & cinnamon", "Cozy intimate projection", "Loved by women", "Long lasting"],
    cons: ["Best in cooler settings", "Rich sweetness"],
    whenToApply: [
      { icon: "Heart", label: "Dates", detail: "Intimate date nights" },
      { icon: "Moon", label: "Evening", detail: "Dinner & lounge" },
      { icon: "PartyPopper", label: "Social", detail: "Evening hangouts" },
    ],
  },
  {
    id: "SA-031",
    name: "Dior Sauvage Elixir",
    actual: 320,
    original: 540,
    tag: "Men's Perfume",
    category: "mens",
    image: "/perfume10.jpg",
    desc: "Nutmeg, cardamom, cinnamon, lavender, and rich licorice woods — ultra-concentrated masculine power.",
    perfectOccasion: "High-status events, boss meetings, night celebrations",
    pros: ["Massive projection & silage", "Most respected modern men's perfume", "Lasts 24+ hours", "Supreme executive scent"],
    cons: ["Very potent (2 sprays max)", "Night/cool weather best"],
    whenToApply: [
      { icon: "Sunrise", label: "Morning", detail: "Daily morning boost" },
      { icon: "Briefcase", label: "Office", detail: "Boardroom authority" },
      { icon: "Moon", label: "Night", detail: "Night out" },
    ],
  },
  {
    id: "SA-032",
    name: "Creed Aventus For Men",
    actual: 350,
    original: 590,
    tag: "Men's Perfume",
    category: "mens",
    image: "/perfume11.jpg",
    desc: "Pineapple, bergamot, blackcurrant, birch smoke, and oakmoss — the King of luxury perfumes.",
    perfectOccasion: "VIP executive meetings, celebrations, luxury weddings",
    pros: ["Timeless prestige DNA", "Fruity smoky balance", "High-status perception", "Year-round performance"],
    cons: ["High demand", "Sophisticated profile"],
    whenToApply: [
      { icon: "Briefcase", label: "Office", detail: "Executive meetings" },
      { icon: "Landmark", label: "Formal", detail: "Gala & celebrations" },
      { icon: "Sun", label: "Daytime", detail: "Signature scent" },
    ],
  },
  {
    id: "SA-033",
    name: "YSL Black Opium Eau De Parfum",
    actual: 270,
    original: 450,
    tag: "Women's Perfume",
    category: "womens",
    image: "/perfume12.jpg",
    desc: "Black coffee accord, orange blossom, white flowers, and warm vanilla — seductive, energetic, and glamorous.",
    perfectOccasion: "Parties, clubbing, romantic late dinners, dates",
    pros: ["Energetic coffee and vanilla", "Bold sensual attraction", "Nightlife favourite", "Instant mood lifter"],
    cons: ["Night wear focused", "Sweet and punchy"],
    whenToApply: [
      { icon: "Moon", label: "Night", detail: "Parties & clubs" },
      { icon: "Heart", label: "Romantic", detail: "Date nights" },
      { icon: "PartyPopper", label: "Events", detail: "Evening socials" },
    ],
  },
  {
    id: "SA-034",
    name: "Lattafa Nebras (Vanilla & Cacao)",
    actual: 240,
    original: 400,
    tag: "Unisex Perfume",
    category: "unisex",
    image: "/perfume13.jpg",
    desc: "Red berries, mandarin, cacao, vanilla, and tonka bean — the viral Arabian chocolate vanilla gourmand.",
    perfectOccasion: "Casual, cozy hangouts, evening dates, church",
    pros: ["Rich chocolate & berries", "Warm cozy aura", "Delicious gourmand trail", "Long lasting"],
    cons: ["Very edible sweet profile", "Moderate warmth required"],
    whenToApply: [
      { icon: "Sun", label: "Daytime", detail: "Cozy daytime wear" },
      { icon: "Heart", label: "Dates", detail: "Sweet date moments" },
      { icon: "ShoppingBag", label: "Casual", detail: "Daily indulgence" },
    ],
  },
  {
    id: "SA-035",
    name: "Lattafa Bade'e Al Oud (Oud for Glory)",
    actual: 260,
    original: 440,
    tag: "Unisex Perfume",
    category: "unisex",
    image: "/perfume14.jpg",
    desc: "Natural oud wood, lavender, saffron, and nutmeg — deep, smoky, majestic, and revered in Ghana.",
    perfectOccasion: "Traditional weddings, grand durbars, VIP events",
    pros: ["Regal oud & saffron", "Uncompromising projection", "Majestic royal aura", "24hr staying power"],
    cons: ["Bold oud notes", "For confident wearers"],
    whenToApply: [
      { icon: "Landmark", label: "Events", detail: "Traditional & royal events" },
      { icon: "Moon", label: "Evening", detail: "Grand celebrations" },
      { icon: "Briefcase", label: "VIP", detail: "VIP functions" },
    ],
  },
  {
    id: "SA-036",
    name: "Scentiva Deluxe 3-in-1 Discovery Box",
    actual: 390,
    original: 650,
    tag: "Gift Set",
    category: "gift",
    image: "/perfme15.jpg",
    desc: "A curated 3-piece luxury fragrance box featuring top best-sellers with gold gift packaging and custom ribbon.",
    perfectOccasion: "Birthdays, anniversaries, corporate gifts, bridal showers",
    pros: ["3 best-selling perfumes in one", "Luxury ribbon box presentation", "Huge savings bundle", "Perfect ready-to-gift"],
    cons: ["Limited gift edition stock", "Gift box sizing"],
    whenToApply: [
      { icon: "Gift", label: "Gifting", detail: "Birthday & anniversary" },
      { icon: "Landmark", label: "Corporate", detail: "VIP client gifting" },
      { icon: "Heart", label: "Special", detail: "Romantic surprises" },
    ],
  },
  {
    id: "SA-037",
    name: "Scentiva His & Hers Duo Gift Box",
    actual: 320,
    original: 540,
    tag: "Gift Set",
    category: "gift",
    image: "/perfume16.jpg",
    desc: "His & Hers complementary luxury fragrances packed together in an elegant velvet-lined presentation box.",
    perfectOccasion: "Couples, weddings, Valentine's, housewarming",
    pros: ["His & Hers matching pairing", "Elegant velvet gift packaging", "40% discount bundle", "Ideal couple gift"],
    cons: ["Fixed fragrance pairing", "Limited seasonal runs"],
    whenToApply: [
      { icon: "Heart", label: "Couples", detail: "Anniversary & Valentine" },
      { icon: "Gift", label: "Gifting", detail: "Weddings & showers" },
      { icon: "Landmark", label: "Occasions", detail: "Special milestones" },
    ],
  },
  {
    id: "SA-038",
    name: "Scentiva Royal VIP Fragrance Hamper",
    actual: 480,
    original: 800,
    tag: "Luxury Gift Hamper",
    category: "gift",
    image: "/gift.png",
    desc: "The ultimate luxury gift hamper: 2 full-sized perfumes, 1 body mist, scented candle & personalized gift card.",
    perfectOccasion: "Premium luxury gifting, Mother's/Father's day, festive seasons",
    pros: ["Complete fragrance luxury bundle", "Includes body mist & candle", "Custom handwritten gift note", "Supreme luxury value"],
    cons: ["Premium hamper package", "Requires advance order for custom notes"],
    whenToApply: [
      { icon: "Gift", label: "Ultimate Gift", detail: "Grand celebrations" },
      { icon: "Heart", label: "Surprises", detail: "Loved ones & spouses" },
      { icon: "Landmark", label: "Festive", detail: "Christmas & holidays" },
    ],
  },
];

export const allProducts = withLaunchPricing(rawProducts);
