import type { Product } from "@/components/ProductModal";

export const allProducts: Product[] = [
  {
    id: "SA-001", name: "Oud Noir Elite", actual: 320, original: 380,
    tag: "Men's Perfume", category: "mens", image: "/perfume1.jpg",
    desc: "A bold, smoky oud with hints of black amber — perfect for confident evenings.",
    perfectOccasion: "Formal Night Events",
    pros: [ "Exceptional longevity", "Commanding sillage", "Ideal base note", "Unique signature" ],
    cons: [ "Intense opening", "Not for office", "Best on warm skin" ],
    whenToApply: [
      { icon: "Moon", label: "Evening", detail: "Dinner & night events" },
      { icon: "Heart", label: "Date Night", detail: "Romantic occasions" },
      { icon: "Landmark", label: "Formal Affairs", detail: "Weddings & galas" },
    ],
  },
  {
    id: "SA-002", name: "Rose Velvet", actual: 280, original: 330,
    tag: "Women's Perfume", category: "womens", image: "/perfume2.jpg",
    desc: "Soft rose petals wrapped in warm musk — effortlessly feminine all day.",
    perfectOccasion: "Office & Professional",
    pros: [ "Delicate yet long-lasting", "Universally loved floral", "Light enough for daily wear", "Excellent for gifting" ],
    cons: [ "May fade on dry skin", "Strongly feminine" ],
    whenToApply: [
      { icon: "Sun", label: "Daytime", detail: "Casual & errands" },
      { icon: "GraduationCap", label: "Campus", detail: "Students & lectures" },
      { icon: "Briefcase", label: "Work", detail: "Professional settings" },
    ],
  },
  {
    id: "SA-003", name: "Midnight Fusion", actual: 260, original: 300,
    tag: "Unisex Body Spray", category: "unisex", image: "/perfume3.jpg",
    desc: "Fresh citrus collides with dark woods — a versatile everyday spray.",
    perfectOccasion: "Gym & Sports",
    pros: [ "Gender-neutral", "Ideal for tropical weather", "Affordable price", "Fast-drying formula" ],
    cons: [ "Moderate longevity", "Less suited for formal" ],
    whenToApply: [
      { icon: "Sunrise", label: "Morning", detail: "Start your day fresh" },
      { icon: "Dumbbell", label: "Active", detail: "Gym & outdoor activities" },
      { icon: "Backpack", label: "Daily", detail: "Campus & everyday use" },
    ],
  },
  {
    id: "SA-004", name: "Amber & Woods", actual: 340, original: 400,
    tag: "Men's Perfume", category: "mens", image: "/perfum4.jpg",
    status: "sold-out",
    desc: "Warm amber and rich sandalwood for the modern gentleman.",
    perfectOccasion: "Business Meetings",
    pros: [ "Warm and inviting", "Long-lasting amber", "Conveys confidence", "Barbershop signature" ],
    cons: [ "Heavy fragrance", "Not for hot daytime" ],
    whenToApply: [
      { icon: "Moon", label: "Evening", detail: "Cool-weather evenings" },
      { icon: "Briefcase", label: "Business", detail: "Client meetings" },
      { icon: "Scissors", label: "Salon", detail: "Barbershop signature" },
    ],
  },
  {
    id: "SA-005", name: "Floral Silk", actual: 300, original: 360,
    tag: "Women's Perfume", category: "womens", image: "/perfume5.jpg",
    desc: "A luxurious bouquet of peony, jasmine and white cedar.",
    perfectOccasion: "Social Hangouts",
    pros: [ "Multi-layered floral", "Compliment magnet", "Pairs with body oils", "Great projection" ],
    cons: [ "Strong opening", "Not for minimalists" ],
    whenToApply: [
      { icon: "PartyPopper", label: "Social", detail: "Parties & events" },
      { icon: "ShoppingBag", label: "Shopping", detail: "Outings & hangouts" },
      { icon: "Scissors", label: "Salon", detail: "Client-facing roles" },
    ],
  },
  {
    id: "SA-006", name: "Azure Fresh", actual: 230, original: 270,
    tag: "Unisex Body Spray", category: "unisex", image: "/perfume6.jpg",
    desc: "Clean oceanic notes — ideal for morning routines and campus life.",
    perfectOccasion: "Beach & Summer",
    pros: [ "Budget-friendly", "Perfect starter", "Suits Ghana climate", "Clean and presentable" ],
    cons: [ "Light projection", "Shorter wear time" ],
    whenToApply: [
      { icon: "Sunrise", label: "Morning", detail: "Fresh start to the day" },
      { icon: "GraduationCap", label: "Campus", detail: "Lectures & study" },
      { icon: "Dumbbell", label: "Active", detail: "Gym & sports" },
    ],
  },
  {
    id: "SA-007", name: "Gold Santal", actual: 390, original: 450,
    tag: "Men's Perfume", category: "mens", image: "/perfume7.jpg",
    desc: "Dry goldenwood and leather for commanding presence in any room.",
    perfectOccasion: "Boardroom & Executive",
    pros: [ "Unique sandalwood blend", "14+ hour longevity", "Projects authority", "Beautiful drydown" ],
    cons: [ "Premium price", "Very potent" ],
    whenToApply: [
      { icon: "Briefcase", label: "Boardroom", detail: "Executive meetings" },
      { icon: "Moon", label: "Evenings", detail: "High-end dinners" },
      { icon: "Landmark", label: "Formal", detail: "Ceremonies & events" },
    ],
  },
  {
    id: "SA-008", name: "Mystic Jasmine", actual: 310, original: 370,
    tag: "Women's Perfume", category: "womens", image: "/perfume8.jpg",
    desc: "Dreamy jasmine and vanilla — perfect for date nights and gifting.",
    perfectOccasion: "Romantic Dates",
    pros: [ "Sensual jasmine-vanilla", "Beautiful gift option", "8-10 hour wear", "Versatile day/night" ],
    cons: [ "Vanilla can be sweet in heat" ],
    whenToApply: [
      { icon: "Heart", label: "Date Night", detail: "Romantic evenings" },
      { icon: "Gift", label: "Gift Ready", detail: "Perfect as a gift" },
      { icon: "Moon", label: "Night Out", detail: "Clubs & parties" },
    ],
  },
  {
    id: "SA-010", name: "Black Orchid", actual: 360, original: 420,
    tag: "Women's Perfume", category: "womens", image: "/perfume10.jpg",
    desc: "Dark orchid and patchouli for bold women who own the room.",
    perfectOccasion: "Gala & Fashion Events",
    pros: [ "Exotic and rare", "Stunning longevity", "Balanced dark florals", "Fashion-forward" ],
    cons: [ "Bold opening", "Patchouli note" ],
    whenToApply: [
      { icon: "Moon", label: "Night", detail: "Evening & after-dark" },
      { icon: "PartyPopper", label: "Events", detail: "Galas & high fashion" },
      { icon: "Briefcase", label: "Power Look", detail: "Senior professional days" },
    ],
  },
  {
    id: "SA-011", name: "Cedar Storm", actual: 270, original: 320,
    tag: "Men's Perfume", category: "mens", image: "/perfume11.jpg",
    desc: "Crisp cedarwood and cool bergamot for an unstoppable fresh feel.",
    perfectOccasion: "Daily Campus Life",
    pros: [ "Fresh but unique", "Energising bergamot", "Great value", "Versatile setting" ],
    cons: [ "Moderate longevity", "More casual" ],
    whenToApply: [
      { icon: "Sunrise", label: "Morning", detail: "Start the day sharp" },
      { icon: "GraduationCap", label: "Campus", detail: "Students & youth" },
      { icon: "Sun", label: "Daytime", detail: "Casual hangouts" },
    ],
  },
  {
    id: "SA-012", name: "Velvet Date", actual: 450, original: 530,
    tag: "Gift Bundle", category: "gift", image: "/perfume12.jpg",
    desc: "A curated duo of his-and-hers fragrances — the ideal couple's gift.",
    perfectOccasion: "Wedding & Anniversary Gift",
    pros: [ "Two premium scents", "Luxury packaging", "Perfect for couple milestones", "Impressive value" ],
    cons: [ "Bundle only", "Gift specific" ],
    whenToApply: [
      { icon: "Gift", label: "Gift", detail: "Any celebration" },
      { icon: "Heart", label: "Anniversary", detail: "Valentine's & milestones" },
      { icon: "Gift", label: "Birthday", detail: "Luxury birthday gift" },
    ],
  },
  {
    id: "SA-013", name: "Pink Bloom", actual: 295, original: 350,
    tag: "Women's Perfume", category: "womens", image: "/perfume13.jpg",
    desc: "Playful peach blossoms with a warm musky finish.",
    perfectOccasion: "Weekend Outings",
    pros: [ "Youthful scent", "Great for students", "Fun weekend vibe", "Fresh peach notes" ],
    cons: [ "Very youthful", "Can become sweet" ],
    whenToApply: [
      { icon: "GraduationCap", label: "Campus", detail: "Lectures & campus life" },
      { icon: "ShoppingBag", label: "Weekend", detail: "Outings & shopping" },
      { icon: "Sun", label: "Daytime", detail: "Casual daily wear" },
    ],
  },
  {
    id: "SA-014", name: "Aqua Surge", actual: 240, original: 285,
    tag: "Unisex Body Spray", category: "unisex", image: "/perfume14.jpg",
    desc: "A refreshing wave of aquatic notes with green citrus.",
    perfectOccasion: "Post-Workout / Gym",
    pros: [ "Instantly cooling", "Post-gym perfect", "Gender-fluid", "Non-greasy" ],
    cons: [ "Light longevity", "Casual only" ],
    whenToApply: [
      { icon: "Dumbbell", label: "Gym", detail: "After workouts" },
      { icon: "Sunrise", label: "Morning", detail: "Fresh daily start" },
      { icon: "Scissors", label: "Salon", detail: "In between clients" },
    ],
  },
  {
    id: "SA-015", name: "Royal Oud Set", actual: 520, original: 620,
    tag: "Gift Bundle", category: "gift", image: "/perfme15.jpg",
    desc: "A premium gift set featuring 3 signature ouds in a luxury box.",
    perfectOccasion: "High-End Corporate Gift",
    pros: [ "Three curated ouds", "Luxury keepsake box", "High-value gift", "Oud discovery" ],
    cons: [ "Premium price", "Intense oud style" ],
    whenToApply: [
      { icon: "Gift", label: "Gift", detail: "Luxury gifting" },
      { icon: "Moon", label: "Evening", detail: "Special occasions" },
      { icon: "Landmark", label: "Cultural", detail: "Ceremonies" },
    ],
  },
  {
    id: "SA-016", name: "Peach Sorbet", actual: 215, original: 255,
    tag: "Women's Perfume", category: "womens", image: "/perfume16.jpg",
    desc: "Fruity and fun — the go-to scent for young, vibrant women.",
    perfectOccasion: "Casual Daily Wear",
    pros: [ "Most affordable", "Bright and fun", "Perfect entry", "Light and summery" ],
    cons: [ "Shorter wear", "Casual profile" ],
    whenToApply: [
      { icon: "GraduationCap", label: "Campus", detail: "Student lifestyle" },
      { icon: "Sun", label: "Daytime", detail: "Casual everyday wear" },
      { icon: "ShoppingBag", label: "Weekend", detail: "Hangouts & fun days" },
    ],
  },
];
